set(CTEST_SITE "CircleCI 2.0")
set(CTEST_BUILD_NAME "${BUILDNAME}")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_SOURCE_DIRECTORY "/root/project")
set(CTEST_BINARY_DIRECTORY "/root/project/_build")
set(CTEST_UPDATE_COMMAND git)
set(CTEST_UPDATE_VERSION_ONLY 1)

ctest_start(Experimental)
ctest_update()
ctest_configure()

ctest_build(NUMBER_ERRORS num_errors CAPTURE_CMAKE_ERROR cmake_errors)
if ("${num_errors}" GREATER 0)
  message(SEND_ERROR "${num_errors} build errors")
endif()
if ("${cmake_errors}" EQUAL -1)
  message(SEND_ERROR "error running build command")
endif()

ctest_test(RETURN_VALUE test_status CAPTURE_CMAKE_ERROR cmake_errors)
if (NOT "${test_status}" EQUAL 0)
  message(SEND_ERROR "some tests did not pass cleanly")
endif()
if ("${cmake_errors}" EQUAL -1)
  message(SEND_ERROR "error running test command")
endif()

ctest_submit()
